### ISSUE TITLE
Touch-bar not displayed if not enough space / 13Inch Mac not enough space for default configuration

### ISSUE THREAD

**Issue by stefhol** [Augustpi/touch_bar#1]
I guess you use a 16inch Macbook because the 13 inch has in the factory settings not enough space to display the extension Touch Bar in file mode. This gives the illusion that the extension is not working at all.
I only discovered this accidentally as I removed some of the Mac default actions.

**Comment by Augustpi** [comment]
Have you tried adding the ignore list to their settings? I will still check if space is not enough.

  "keyboard.touchbar.ignored": [
    "workbench.action.debug.start",
    "workbench.action.debug.run",
    "workbench.action.debug.restart",
    "workbench.action.debug.stepOver",
    "workbench.action.debug.stepInto",
    "workbench.action.debug.stepOut",
    "workbench.action.debug.pause",
    "workbench.action.debug.disconnect",
    "workbench.action.debug.stop",
    "workbench.action.debug.restartFrame",
    "workbench.action.debug.continue",
    "workbench.action.newWindow",
    "workbench.action.navigateBack",
    "workbench.action.navigateForward"
  ],
